const meetingMinutesTemplate = {
  _id: 'template-meeting',
  name: '会议纪要',
  description: '快速记录会议要点、待办事项和决议',
  category: 'meeting',
  thumbnail: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  icon: '📝',
  width: 3000,
  height: 2000,
  backgroundColor: '#f8f9fa',
  layers: [
    {
      name: '标题区',
      visible: true,
      locked: false,
      order: 0,
      elements: [
        {
          id: 'el-title',
          type: 'text',
          x: 100,
          y: 60,
          width: 600,
          height: 60,
          fill: '#1a1a1a',
          text: '会议纪要',
          fontSize: 36,
          fontWeight: 700,
        },
        {
          id: 'el-subtitle',
          type: 'text',
          x: 100,
          y: 130,
          width: 400,
          height: 30,
          fill: '#6b7280',
          text: '会议主题：___________',
          fontSize: 18,
          fontWeight: 500,
        },
        {
          id: 'el-meta',
          type: 'text',
          x: 100,
          y: 170,
          width: 500,
          height: 24,
          fill: '#6b7280',
          text: '时间：___________    主持人：___________',
          fontSize: 14,
        },
      ],
    },
    {
      name: '议程',
      visible: true,
      locked: false,
      order: 1,
      elements: [
        {
          id: 'el-agenda-bg',
          type: 'rect',
          x: 100,
          y: 230,
          width: 650,
          height: 260,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 8,
        },
        {
          id: 'el-agenda-title',
          type: 'text',
          x: 130,
          y: 250,
          width: 200,
          height: 30,
          fill: '#667eea',
          text: '📋 会议议程',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-agenda-1',
          type: 'sticky-note',
          x: 130,
          y: 300,
          width: 180,
          height: 60,
          fill: '#fef3c7',
          text: '1. 开场介绍',
          fontSize: 14,
        },
        {
          id: 'el-agenda-2',
          type: 'sticky-note',
          x: 330,
          y: 300,
          width: 180,
          height: 60,
          fill: '#dbeafe',
          text: '2. 议题讨论',
          fontSize: 14,
        },
        {
          id: 'el-agenda-3',
          type: 'sticky-note',
          x: 530,
          y: 300,
          width: 180,
          height: 60,
          fill: '#d1fae5',
          text: '3. 总结决议',
          fontSize: 14,
        },
        {
          id: 'el-agenda-4',
          type: 'sticky-note',
          x: 130,
          y: 380,
          width: 180,
          height: 60,
          fill: '#fce7f3',
          text: '4. 待办分配',
          fontSize: 14,
        },
        {
          id: 'el-agenda-5',
          type: 'sticky-note',
          x: 330,
          y: 380,
          width: 180,
          height: 60,
          fill: '#e9d5ff',
          text: '5. 下次安排',
          fontSize: 14,
        },
      ],
    },
    {
      name: '讨论要点',
      visible: true,
      locked: false,
      order: 2,
      elements: [
        {
          id: 'el-points-bg',
          type: 'rect',
          x: 800,
          y: 230,
          width: 650,
          height: 260,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 8,
        },
        {
          id: 'el-points-title',
          type: 'text',
          x: 830,
          y: 250,
          width: 200,
          height: 30,
          fill: '#667eea',
          text: '💡 讨论要点',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-point-1',
          type: 'text',
          x: 830,
          y: 300,
          width: 580,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 14,
        },
        {
          id: 'el-point-2',
          type: 'text',
          x: 830,
          y: 335,
          width: 580,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 14,
        },
        {
          id: 'el-point-3',
          type: 'text',
          x: 830,
          y: 370,
          width: 580,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 14,
        },
        {
          id: 'el-point-4',
          type: 'text',
          x: 830,
          y: 405,
          width: 580,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 14,
        },
      ],
    },
    {
      name: '决议',
      visible: true,
      locked: false,
      order: 3,
      elements: [
        {
          id: 'el-decision-bg',
          type: 'rect',
          x: 100,
          y: 520,
          width: 650,
          height: 260,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 8,
        },
        {
          id: 'el-decision-title',
          type: 'text',
          x: 130,
          y: 540,
          width: 200,
          height: 30,
          fill: '#667eea',
          text: '✅ 会议决议',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-decision-1',
          type: 'text',
          x: 130,
          y: 590,
          width: 580,
          height: 24,
          fill: '#374151',
          text: '1. _______________________________',
          fontSize: 14,
        },
        {
          id: 'el-decision-2',
          type: 'text',
          x: 130,
          y: 625,
          width: 580,
          height: 24,
          fill: '#374151',
          text: '2. _______________________________',
          fontSize: 14,
        },
        {
          id: 'el-decision-3',
          type: 'text',
          x: 130,
          y: 660,
          width: 580,
          height: 24,
          fill: '#374151',
          text: '3. _______________________________',
          fontSize: 14,
        },
      ],
    },
    {
      name: '待办事项',
      visible: true,
      locked: false,
      order: 4,
      elements: [
        {
          id: 'el-todo-bg',
          type: 'rect',
          x: 800,
          y: 520,
          width: 650,
          height: 260,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 8,
        },
        {
          id: 'el-todo-title',
          type: 'text',
          x: 830,
          y: 540,
          width: 200,
          height: 30,
          fill: '#667eea',
          text: '📌 待办事项',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-todo-col-task',
          type: 'text',
          x: 830,
          y: 585,
          width: 200,
          height: 20,
          fill: '#6b7280',
          text: '任务',
          fontSize: 12,
          fontWeight: 600,
        },
        {
          id: 'el-todo-col-owner',
          type: 'text',
          x: 1050,
          y: 585,
          width: 120,
          height: 20,
          fill: '#6b7280',
          text: '负责人',
          fontSize: 12,
          fontWeight: 600,
        },
        {
          id: 'el-todo-col-ddl',
          type: 'text',
          x: 1200,
          y: 585,
          width: 120,
          height: 20,
          fill: '#6b7280',
          text: '截止日期',
          fontSize: 12,
          fontWeight: 600,
        },
        {
          id: 'el-todo-1-task',
          type: 'text',
          x: 830,
          y: 615,
          width: 200,
          height: 24,
          fill: '#374151',
          text: '___________',
          fontSize: 14,
        },
        {
          id: 'el-todo-1-owner',
          type: 'text',
          x: 1050,
          y: 615,
          width: 120,
          height: 24,
          fill: '#374151',
          text: '___________',
          fontSize: 14,
        },
        {
          id: 'el-todo-1-ddl',
          type: 'text',
          x: 1200,
          y: 615,
          width: 120,
          height: 24,
          fill: '#374151',
          text: '___________',
          fontSize: 14,
        },
        {
          id: 'el-todo-2-task',
          type: 'text',
          x: 830,
          y: 650,
          width: 200,
          height: 24,
          fill: '#374151',
          text: '___________',
          fontSize: 14,
        },
        {
          id: 'el-todo-2-owner',
          type: 'text',
          x: 1050,
          y: 650,
          width: 120,
          height: 24,
          fill: '#374151',
          text: '___________',
          fontSize: 14,
        },
        {
          id: 'el-todo-2-ddl',
          type: 'text',
          x: 1200,
          y: 650,
          width: 120,
          height: 24,
          fill: '#374151',
          text: '___________',
          fontSize: 14,
        },
        {
          id: 'el-todo-3-task',
          type: 'text',
          x: 830,
          y: 685,
          width: 200,
          height: 24,
          fill: '#374151',
          text: '___________',
          fontSize: 14,
        },
        {
          id: 'el-todo-3-owner',
          type: 'text',
          x: 1050,
          y: 685,
          width: 120,
          height: 24,
          fill: '#374151',
          text: '___________',
          fontSize: 14,
        },
        {
          id: 'el-todo-3-ddl',
          type: 'text',
          x: 1200,
          y: 685,
          width: 120,
          height: 24,
          fill: '#374151',
          text: '___________',
          fontSize: 14,
        },
      ],
    },
    {
      name: '参会人员',
      visible: true,
      locked: false,
      order: 5,
      elements: [
        {
          id: 'el-attend-bg',
          type: 'rect',
          x: 1500,
          y: 230,
          width: 350,
          height: 550,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 8,
        },
        {
          id: 'el-attend-title',
          type: 'text',
          x: 1530,
          y: 250,
          width: 200,
          height: 30,
          fill: '#667eea',
          text: '👥 参会人员',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-attend-1',
          type: 'text',
          x: 1530,
          y: 300,
          width: 280,
          height: 24,
          fill: '#374151',
          text: '□ ________________',
          fontSize: 14,
        },
        {
          id: 'el-attend-2',
          type: 'text',
          x: 1530,
          y: 335,
          width: 280,
          height: 24,
          fill: '#374151',
          text: '□ ________________',
          fontSize: 14,
        },
        {
          id: 'el-attend-3',
          type: 'text',
          x: 1530,
          y: 370,
          width: 280,
          height: 24,
          fill: '#374151',
          text: '□ ________________',
          fontSize: 14,
        },
        {
          id: 'el-attend-4',
          type: 'text',
          x: 1530,
          y: 405,
          width: 280,
          height: 24,
          fill: '#374151',
          text: '□ ________________',
          fontSize: 14,
        },
        {
          id: 'el-attend-5',
          type: 'text',
          x: 1530,
          y: 440,
          width: 280,
          height: 24,
          fill: '#374151',
          text: '□ ________________',
          fontSize: 14,
        },
        {
          id: 'el-attend-6',
          type: 'text',
          x: 1530,
          y: 475,
          width: 280,
          height: 24,
          fill: '#374151',
          text: '□ ________________',
          fontSize: 14,
        },
        {
          id: 'el-attend-7',
          type: 'text',
          x: 1530,
          y: 510,
          width: 280,
          height: 24,
          fill: '#374151',
          text: '□ ________________',
          fontSize: 14,
        },
        {
          id: 'el-attend-8',
          type: 'text',
          x: 1530,
          y: 545,
          width: 280,
          height: 24,
          fill: '#374151',
          text: '□ ________________',
          fontSize: 14,
        },
        {
          id: 'el-attend-9',
          type: 'text',
          x: 1530,
          y: 580,
          width: 280,
          height: 24,
          fill: '#374151',
          text: '□ ________________',
          fontSize: 14,
        },
        {
          id: 'el-attend-10',
          type: 'text',
          x: 1530,
          y: 615,
          width: 280,
          height: 24,
          fill: '#374151',
          text: '□ ________________',
          fontSize: 14,
        },
      ],
    },
  ],
};

const workflowTemplate = {
  _id: 'template-workflow',
  name: '流程梳理',
  description: '可视化梳理业务流程、工作流和决策路径',
  category: 'workflow',
  thumbnail: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  icon: '🔄',
  width: 3500,
  height: 2200,
  backgroundColor: '#f0f9ff',
  layers: [
    {
      name: '标题区',
      visible: true,
      locked: false,
      order: 0,
      elements: [
        {
          id: 'el-title',
          type: 'text',
          x: 100,
          y: 60,
          width: 600,
          height: 60,
          fill: '#1a1a1a',
          text: '流程梳理',
          fontSize: 36,
          fontWeight: 700,
        },
        {
          id: 'el-subtitle',
          type: 'text',
          x: 100,
          y: 130,
          width: 500,
          height: 30,
          fill: '#6b7280',
          text: '流程名称：___________    版本：V1.0',
          fontSize: 18,
          fontWeight: 500,
        },
      ],
    },
    {
      name: '流程图例',
      visible: true,
      locked: false,
      order: 1,
      elements: [
        {
          id: 'el-legend-bg',
          type: 'rect',
          x: 2800,
          y: 60,
          width: 500,
          height: 180,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 8,
        },
        {
          id: 'el-legend-title',
          type: 'text',
          x: 2830,
          y: 85,
          width: 200,
          height: 24,
          fill: '#0284c7',
          text: '📖 图例说明',
          fontSize: 16,
          fontWeight: 600,
        },
        {
          id: 'el-legend-start',
          type: 'rect',
          x: 2830,
          y: 125,
          width: 80,
          height: 32,
          fill: '#10b981',
          stroke: '#059669',
          strokeWidth: 2,
          borderRadius: 16,
        },
        {
          id: 'el-legend-start-text',
          type: 'text',
          x: 2920,
          y: 130,
          width: 150,
          height: 24,
          fill: '#374151',
          text: '开始/结束',
          fontSize: 14,
        },
        {
          id: 'el-legend-process',
          type: 'rect',
          x: 2830,
          y: 165,
          width: 80,
          height: 32,
          fill: '#3b82f6',
          stroke: '#2563eb',
          strokeWidth: 2,
          borderRadius: 4,
        },
        {
          id: 'el-legend-process-text',
          type: 'text',
          x: 2920,
          y: 170,
          width: 150,
          height: 24,
          fill: '#374151',
          text: '处理步骤',
          fontSize: 14,
        },
        {
          id: 'el-legend-decision',
          type: 'text',
          x: 2840,
          y: 210,
          width: 60,
          height: 32,
          fill: '#f59e0b',
          text: '◆',
          fontSize: 32,
          fontWeight: 700,
        },
        {
          id: 'el-legend-decision-text',
          type: 'text',
          x: 2920,
          y: 210,
          width: 150,
          height: 24,
          fill: '#374151',
          text: '决策判断',
          fontSize: 14,
        },
      ],
    },
    {
      name: '主流程 - 第一阶段',
      visible: true,
      locked: false,
      order: 2,
      elements: [
        {
          id: 'el-start',
          type: 'rect',
          x: 100,
          y: 350,
          width: 160,
          height: 60,
          fill: '#10b981',
          stroke: '#059669',
          strokeWidth: 2,
          borderRadius: 30,
        },
        {
          id: 'el-start-text',
          type: 'text',
          x: 100,
          y: 365,
          width: 160,
          height: 30,
          fill: '#ffffff',
          text: '开始',
          fontSize: 18,
          fontWeight: 600,
          textAlign: 'center',
        },
        {
          id: 'el-arrow-1',
          type: 'line',
          x: 260,
          y: 380,
          width: 100,
          height: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          points: [260, 380, 350, 380],
        },
        {
          id: 'el-arrowhead-1',
          type: 'text',
          x: 345,
          y: 372,
          width: 20,
          height: 20,
          fill: '#6b7280',
          text: '→',
          fontSize: 24,
          fontWeight: 700,
        },
        {
          id: 'el-step-1',
          type: 'rect',
          x: 370,
          y: 330,
          width: 200,
          height: 100,
          fill: '#3b82f6',
          stroke: '#2563eb',
          strokeWidth: 2,
          borderRadius: 8,
        },
        {
          id: 'el-step-1-text',
          type: 'text',
          x: 370,
          y: 355,
          width: 200,
          height: 50,
          fill: '#ffffff',
          text: '步骤1\n需求收集',
          fontSize: 16,
          fontWeight: 600,
          textAlign: 'center',
          lineHeight: 1.5,
        },
        {
          id: 'el-step-1-desc',
          type: 'text',
          x: 370,
          y: 440,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '负责人：___________',
          fontSize: 12,
          textAlign: 'center',
        },
        {
          id: 'el-arrow-2',
          type: 'line',
          x: 570,
          y: 380,
          width: 100,
          height: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          points: [570, 380, 660, 380],
        },
        {
          id: 'el-arrowhead-2',
          type: 'text',
          x: 655,
          y: 372,
          width: 20,
          height: 20,
          fill: '#6b7280',
          text: '→',
          fontSize: 24,
          fontWeight: 700,
        },
        {
          id: 'el-step-2',
          type: 'rect',
          x: 680,
          y: 330,
          width: 200,
          height: 100,
          fill: '#3b82f6',
          stroke: '#2563eb',
          strokeWidth: 2,
          borderRadius: 8,
        },
        {
          id: 'el-step-2-text',
          type: 'text',
          x: 680,
          y: 355,
          width: 200,
          height: 50,
          fill: '#ffffff',
          text: '步骤2\n方案设计',
          fontSize: 16,
          fontWeight: 600,
          textAlign: 'center',
          lineHeight: 1.5,
        },
        {
          id: 'el-step-2-desc',
          type: 'text',
          x: 680,
          y: 440,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '负责人：___________',
          fontSize: 12,
          textAlign: 'center',
        },
        {
          id: 'el-arrow-3',
          type: 'line',
          x: 880,
          y: 380,
          width: 100,
          height: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          points: [880, 380, 970, 380],
        },
        {
          id: 'el-arrowhead-3',
          type: 'text',
          x: 965,
          y: 372,
          width: 20,
          height: 20,
          fill: '#6b7280',
          text: '→',
          fontSize: 24,
          fontWeight: 700,
        },
        {
          id: 'el-decision-1',
          type: 'text',
          x: 980,
          y: 340,
          width: 120,
          height: 80,
          fill: '#f59e0b',
          text: '◆',
          fontSize: 120,
          fontWeight: 700,
          textAlign: 'center',
        },
        {
          id: 'el-decision-1-text',
          type: 'text',
          x: 980,
          y: 355,
          width: 120,
          height: 50,
          fill: '#ffffff',
          text: '方案\n评审',
          fontSize: 14,
          fontWeight: 700,
          textAlign: 'center',
          lineHeight: 1.5,
        },
      ],
    },
    {
      name: '主流程 - 分支',
      visible: true,
      locked: false,
      order: 3,
      elements: [
        {
          id: 'el-arrow-yes',
          type: 'line',
          x: 1100,
          y: 350,
          width: 80,
          height: 0,
          stroke: '#10b981',
          strokeWidth: 2,
          points: [1100, 350, 1180, 350],
        },
        {
          id: 'el-arrowhead-yes',
          type: 'text',
          x: 1175,
          y: 342,
          width: 20,
          height: 20,
          fill: '#10b981',
          text: '→',
          fontSize: 24,
          fontWeight: 700,
        },
        {
          id: 'el-label-yes',
          type: 'text',
          x: 1120,
          y: 320,
          width: 50,
          height: 20,
          fill: '#10b981',
          text: '通过',
          fontSize: 12,
          fontWeight: 600,
        },
        {
          id: 'el-step-3-yes',
          type: 'rect',
          x: 1200,
          y: 300,
          width: 200,
          height: 100,
          fill: '#3b82f6',
          stroke: '#2563eb',
          strokeWidth: 2,
          borderRadius: 8,
        },
        {
          id: 'el-step-3-yes-text',
          type: 'text',
          x: 1200,
          y: 325,
          width: 200,
          height: 50,
          fill: '#ffffff',
          text: '步骤3\n开发实现',
          fontSize: 16,
          fontWeight: 600,
          textAlign: 'center',
          lineHeight: 1.5,
        },
        {
          id: 'el-arrow-no',
          type: 'line',
          x: 1040,
          y: 420,
          width: 0,
          height: 80,
          stroke: '#ef4444',
          strokeWidth: 2,
          points: [1040, 420, 1040, 500],
        },
        {
          id: 'el-arrowhead-no',
          type: 'text',
          x: 1032,
          y: 490,
          width: 20,
          height: 20,
          fill: '#ef4444',
          text: '↓',
          fontSize: 24,
          fontWeight: 700,
        },
        {
          id: 'el-label-no',
          type: 'text',
          x: 1050,
          y: 450,
          width: 50,
          height: 20,
          fill: '#ef4444',
          text: '不通过',
          fontSize: 12,
          fontWeight: 600,
        },
        {
          id: 'el-step-3-no',
          type: 'rect',
          x: 860,
          y: 520,
          width: 200,
          height: 80,
          fill: '#f97316',
          stroke: '#ea580c',
          strokeWidth: 2,
          borderRadius: 8,
        },
        {
          id: 'el-step-3-no-text',
          type: 'text',
          x: 860,
          y: 535,
          width: 200,
          height: 50,
          fill: '#ffffff',
          text: '修改方案\n重新评审',
          fontSize: 14,
          fontWeight: 600,
          textAlign: 'center',
          lineHeight: 1.5,
        },
        {
          id: 'el-arrow-back',
          type: 'line',
          x: 760,
          y: 560,
          width: 0,
          height: 150,
          stroke: '#6b7280',
          strokeWidth: 2,
          points: [760, 560, 760, 410, 960, 410],
        },
      ],
    },
    {
      name: '主流程 - 第二阶段',
      visible: true,
      locked: false,
      order: 4,
      elements: [
        {
          id: 'el-arrow-4',
          type: 'line',
          x: 1400,
          y: 350,
          width: 100,
          height: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          points: [1400, 350, 1500, 350],
        },
        {
          id: 'el-arrowhead-4',
          type: 'text',
          x: 1495,
          y: 342,
          width: 20,
          height: 20,
          fill: '#6b7280',
          text: '→',
          fontSize: 24,
          fontWeight: 700,
        },
        {
          id: 'el-step-4',
          type: 'rect',
          x: 1520,
          y: 300,
          width: 200,
          height: 100,
          fill: '#3b82f6',
          stroke: '#2563eb',
          strokeWidth: 2,
          borderRadius: 8,
        },
        {
          id: 'el-step-4-text',
          type: 'text',
          x: 1520,
          y: 325,
          width: 200,
          height: 50,
          fill: '#ffffff',
          text: '步骤4\n测试验证',
          fontSize: 16,
          fontWeight: 600,
          textAlign: 'center',
          lineHeight: 1.5,
        },
        {
          id: 'el-step-4-desc',
          type: 'text',
          x: 1520,
          y: 410,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '负责人：___________',
          fontSize: 12,
          textAlign: 'center',
        },
        {
          id: 'el-arrow-5',
          type: 'line',
          x: 1720,
          y: 350,
          width: 100,
          height: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          points: [1720, 350, 1820, 350],
        },
        {
          id: 'el-arrowhead-5',
          type: 'text',
          x: 1815,
          y: 342,
          width: 20,
          height: 20,
          fill: '#6b7280',
          text: '→',
          fontSize: 24,
          fontWeight: 700,
        },
        {
          id: 'el-step-5',
          type: 'rect',
          x: 1840,
          y: 300,
          width: 200,
          height: 100,
          fill: '#3b82f6',
          stroke: '#2563eb',
          strokeWidth: 2,
          borderRadius: 8,
        },
        {
          id: 'el-step-5-text',
          type: 'text',
          x: 1840,
          y: 325,
          width: 200,
          height: 50,
          fill: '#ffffff',
          text: '步骤5\n发布上线',
          fontSize: 16,
          fontWeight: 600,
          textAlign: 'center',
          lineHeight: 1.5,
        },
        {
          id: 'el-step-5-desc',
          type: 'text',
          x: 1840,
          y: 410,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '负责人：___________',
          fontSize: 12,
          textAlign: 'center',
        },
        {
          id: 'el-arrow-6',
          type: 'line',
          x: 2040,
          y: 350,
          width: 100,
          height: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          points: [2040, 350, 2140, 350],
        },
        {
          id: 'el-arrowhead-6',
          type: 'text',
          x: 2135,
          y: 342,
          width: 20,
          height: 20,
          fill: '#6b7280',
          text: '→',
          fontSize: 24,
          fontWeight: 700,
        },
        {
          id: 'el-end',
          type: 'rect',
          x: 2160,
          y: 320,
          width: 160,
          height: 60,
          fill: '#10b981',
          stroke: '#059669',
          strokeWidth: 2,
          borderRadius: 30,
        },
        {
          id: 'el-end-text',
          type: 'text',
          x: 2160,
          y: 335,
          width: 160,
          height: 30,
          fill: '#ffffff',
          text: '结束',
          fontSize: 18,
          fontWeight: 600,
          textAlign: 'center',
        },
      ],
    },
    {
      name: '备注区',
      visible: true,
      locked: false,
      order: 5,
      elements: [
        {
          id: 'el-note-bg',
          type: 'rect',
          x: 100,
          y: 680,
          width: 2800,
          height: 200,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 8,
        },
        {
          id: 'el-note-title',
          type: 'text',
          x: 130,
          y: 700,
          width: 200,
          height: 30,
          fill: '#0284c7',
          text: '📝 备注与异常处理',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-note-1',
          type: 'sticky-note',
          x: 130,
          y: 750,
          width: 400,
          height: 100,
          fill: '#fef3c7',
          text: '异常情况1：\n_______________',
          fontSize: 14,
        },
        {
          id: 'el-note-2',
          type: 'sticky-note',
          x: 560,
          y: 750,
          width: 400,
          height: 100,
          fill: '#dbeafe',
          text: '异常情况2：\n_______________',
          fontSize: 14,
        },
        {
          id: 'el-note-3',
          type: 'sticky-note',
          x: 990,
          y: 750,
          width: 400,
          height: 100,
          fill: '#d1fae5',
          text: '注意事项：\n_______________',
          fontSize: 14,
        },
        {
          id: 'el-note-4',
          type: 'sticky-note',
          x: 1420,
          y: 750,
          width: 400,
          height: 100,
          fill: '#fce7f3',
          text: '依赖系统：\n_______________',
          fontSize: 14,
        },
        {
          id: 'el-note-5',
          type: 'sticky-note',
          x: 1850,
          y: 750,
          width: 400,
          height: 100,
          fill: '#e9d5ff',
          text: '参考文档：\n_______________',
          fontSize: 14,
        },
      ],
    },
  ],
};

const weeklyPlanTemplate = {
  _id: 'template-weekly',
  name: '周计划',
  description: '规划一周工作，跟踪每日任务和重要事项',
  category: 'productivity',
  thumbnail: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
  icon: '📅',
  width: 3200,
  height: 2000,
  backgroundColor: '#f0fdf4',
  layers: [
    {
      name: '标题和概览',
      visible: true,
      locked: false,
      order: 0,
      elements: [
        {
          id: 'el-title',
          type: 'text',
          x: 100,
          y: 60,
          width: 500,
          height: 60,
          fill: '#1a1a1a',
          text: '周计划',
          fontSize: 36,
          fontWeight: 700,
        },
        {
          id: 'el-week-range',
          type: 'text',
          x: 100,
          y: 130,
          width: 600,
          height: 30,
          fill: '#6b7280',
          text: '2024年 第 ___ 周  ( ___月___日 至 ___月___日 )',
          fontSize: 18,
          fontWeight: 500,
        },
        {
          id: 'el-motto-bg',
          type: 'rect',
          x: 100,
          y: 180,
          width: 700,
          height: 80,
          fill: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
          borderRadius: 12,
        },
        {
          id: 'el-motto-icon',
          type: 'text',
          x: 130,
          y: 200,
          width: 40,
          height: 40,
          fill: '#ffffff',
          text: '💪',
          fontSize: 32,
        },
        {
          id: 'el-motto-text',
          type: 'text',
          x: 180,
          y: 195,
          width: 580,
          height: 50,
          fill: '#ffffff',
          text: '本周目标：\n____________________________________',
          fontSize: 16,
          fontWeight: 600,
          lineHeight: 1.6,
        },
      ],
    },
    {
      name: '周重点',
      visible: true,
      locked: false,
      order: 1,
      elements: [
        {
          id: 'el-focus-bg',
          type: 'rect',
          x: 850,
          y: 60,
          width: 450,
          height: 200,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-focus-title',
          type: 'text',
          x: 880,
          y: 85,
          width: 200,
          height: 24,
          fill: '#059669',
          text: '🎯 本周重点 (3件事)',
          fontSize: 16,
          fontWeight: 600,
        },
        {
          id: 'el-focus-1',
          type: 'text',
          x: 880,
          y: 125,
          width: 380,
          height: 24,
          fill: '#374151',
          text: '1. ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-focus-2',
          type: 'text',
          x: 880,
          y: 160,
          width: 380,
          height: 24,
          fill: '#374151',
          text: '2. ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-focus-3',
          type: 'text',
          x: 880,
          y: 195,
          width: 380,
          height: 24,
          fill: '#374151',
          text: '3. ___________________________',
          fontSize: 14,
        },
      ],
    },
    {
      name: '学习与成长',
      visible: true,
      locked: false,
      order: 2,
      elements: [
        {
          id: 'el-learn-bg',
          type: 'rect',
          x: 1350,
          y: 60,
          width: 450,
          height: 200,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-learn-title',
          type: 'text',
          x: 1380,
          y: 85,
          width: 200,
          height: 24,
          fill: '#059669',
          text: '📚 学习与成长',
          fontSize: 16,
          fontWeight: 600,
        },
        {
          id: 'el-learn-1',
          type: 'text',
          x: 1380,
          y: 125,
          width: 380,
          height: 24,
          fill: '#374151',
          text: '• 阅读：_______________',
          fontSize: 14,
        },
        {
          id: 'el-learn-2',
          type: 'text',
          x: 1380,
          y: 160,
          width: 380,
          height: 24,
          fill: '#374151',
          text: '• 课程：_______________',
          fontSize: 14,
        },
        {
          id: 'el-learn-3',
          type: 'text',
          x: 1380,
          y: 195,
          width: 380,
          height: 24,
          fill: '#374151',
          text: '• 技能：_______________',
          fontSize: 14,
        },
      ],
    },
    {
      name: '健康与生活',
      visible: true,
      locked: false,
      order: 3,
      elements: [
        {
          id: 'el-health-bg',
          type: 'rect',
          x: 1850,
          y: 60,
          width: 450,
          height: 200,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-health-title',
          type: 'text',
          x: 1880,
          y: 85,
          width: 200,
          height: 24,
          fill: '#059669',
          text: '❤️ 健康与生活',
          fontSize: 16,
          fontWeight: 600,
        },
        {
          id: 'el-health-1',
          type: 'text',
          x: 1880,
          y: 125,
          width: 380,
          height: 24,
          fill: '#374151',
          text: '🏃 运动：___ 次',
          fontSize: 14,
        },
        {
          id: 'el-health-2',
          type: 'text',
          x: 1880,
          y: 160,
          width: 380,
          height: 24,
          fill: '#374151',
          text: '😴 早睡：___ 天',
          fontSize: 14,
        },
        {
          id: 'el-health-3',
          type: 'text',
          x: 1880,
          y: 195,
          width: 380,
          height: 24,
          fill: '#374151',
          text: '🎉 休闲：_______________',
          fontSize: 14,
        },
      ],
    },
    {
      name: '每日计划 - 周一二',
      visible: true,
      locked: false,
      order: 4,
      elements: [
        {
          id: 'el-mon-bg',
          type: 'rect',
          x: 100,
          y: 300,
          width: 480,
          height: 700,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-mon-header',
          type: 'rect',
          x: 100,
          y: 300,
          width: 480,
          height: 50,
          fill: '#3b82f6',
          borderTopLeftRadius: 12,
          borderTopRightRadius: 12,
        },
        {
          id: 'el-mon-title',
          type: 'text',
          x: 120,
          y: 310,
          width: 200,
          height: 30,
          fill: '#ffffff',
          text: '🌅 周一 (Mon)',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-mon-date',
          type: 'text',
          x: 380,
          y: 315,
          width: 180,
          height: 24,
          fill: '#ffffff',
          text: '___月___日',
          fontSize: 14,
          textAlign: 'right',
        },
        {
          id: 'el-mon-task-1',
          type: 'text',
          x: 130,
          y: 370,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-mon-task-2',
          type: 'text',
          x: 130,
          y: 405,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-mon-task-3',
          type: 'text',
          x: 130,
          y: 440,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-mon-task-4',
          type: 'text',
          x: 130,
          y: 475,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-mon-task-5',
          type: 'text',
          x: 130,
          y: 510,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-mon-meeting-title',
          type: 'text',
          x: 130,
          y: 560,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '📅 会议安排',
          fontSize: 13,
          fontWeight: 600,
        },
        {
          id: 'el-mon-meeting-1',
          type: 'text',
          x: 130,
          y: 590,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '• ___:___  ___________________',
          fontSize: 13,
        },
        {
          id: 'el-mon-meeting-2',
          type: 'text',
          x: 130,
          y: 620,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '• ___:___  ___________________',
          fontSize: 13,
        },
        {
          id: 'el-mon-note-title',
          type: 'text',
          x: 130,
          y: 665,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '📝 备注',
          fontSize: 13,
          fontWeight: 600,
        },
        {
          id: 'el-mon-note',
          type: 'text',
          x: 130,
          y: 695,
          width: 420,
          height: 40,
          fill: '#374151',
          text: '___________________________',
          fontSize: 13,
        },
        {
          id: 'el-mon-mood',
          type: 'text',
          x: 130,
          y: 750,
          width: 420,
          height: 24,
          fill: '#6b7280',
          text: '今日心情：😊 😐 😔       效率评分：___ / 10',
          fontSize: 13,
        },
        {
          id: 'el-tue-bg',
          type: 'rect',
          x: 620,
          y: 300,
          width: 480,
          height: 700,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-tue-header',
          type: 'rect',
          x: 620,
          y: 300,
          width: 480,
          height: 50,
          fill: '#8b5cf6',
          borderTopLeftRadius: 12,
          borderTopRightRadius: 12,
        },
        {
          id: 'el-tue-title',
          type: 'text',
          x: 640,
          y: 310,
          width: 200,
          height: 30,
          fill: '#ffffff',
          text: '✨ 周二 (Tue)',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-tue-date',
          type: 'text',
          x: 900,
          y: 315,
          width: 180,
          height: 24,
          fill: '#ffffff',
          text: '___月___日',
          fontSize: 14,
          textAlign: 'right',
        },
        {
          id: 'el-tue-task-1',
          type: 'text',
          x: 650,
          y: 370,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-tue-task-2',
          type: 'text',
          x: 650,
          y: 405,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-tue-task-3',
          type: 'text',
          x: 650,
          y: 440,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-tue-task-4',
          type: 'text',
          x: 650,
          y: 475,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-tue-task-5',
          type: 'text',
          x: 650,
          y: 510,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-tue-meeting-title',
          type: 'text',
          x: 650,
          y: 560,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '📅 会议安排',
          fontSize: 13,
          fontWeight: 600,
        },
        {
          id: 'el-tue-meeting-1',
          type: 'text',
          x: 650,
          y: 590,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '• ___:___  ___________________',
          fontSize: 13,
        },
        {
          id: 'el-tue-meeting-2',
          type: 'text',
          x: 650,
          y: 620,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '• ___:___  ___________________',
          fontSize: 13,
        },
        {
          id: 'el-tue-note-title',
          type: 'text',
          x: 650,
          y: 665,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '📝 备注',
          fontSize: 13,
          fontWeight: 600,
        },
        {
          id: 'el-tue-note',
          type: 'text',
          x: 650,
          y: 695,
          width: 420,
          height: 40,
          fill: '#374151',
          text: '___________________________',
          fontSize: 13,
        },
        {
          id: 'el-tue-mood',
          type: 'text',
          x: 650,
          y: 750,
          width: 420,
          height: 24,
          fill: '#6b7280',
          text: '今日心情：😊 😐 😔       效率评分：___ / 10',
          fontSize: 13,
        },
      ],
    },
    {
      name: '每日计划 - 周三四',
      visible: true,
      locked: false,
      order: 5,
      elements: [
        {
          id: 'el-wed-bg',
          type: 'rect',
          x: 1140,
          y: 300,
          width: 480,
          height: 700,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-wed-header',
          type: 'rect',
          x: 1140,
          y: 300,
          width: 480,
          height: 50,
          fill: '#f59e0b',
          borderTopLeftRadius: 12,
          borderTopRightRadius: 12,
        },
        {
          id: 'el-wed-title',
          type: 'text',
          x: 1160,
          y: 310,
          width: 200,
          height: 30,
          fill: '#ffffff',
          text: '☀️ 周三 (Wed)',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-wed-date',
          type: 'text',
          x: 1420,
          y: 315,
          width: 180,
          height: 24,
          fill: '#ffffff',
          text: '___月___日',
          fontSize: 14,
          textAlign: 'right',
        },
        {
          id: 'el-wed-task-1',
          type: 'text',
          x: 1170,
          y: 370,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-wed-task-2',
          type: 'text',
          x: 1170,
          y: 405,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-wed-task-3',
          type: 'text',
          x: 1170,
          y: 440,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-wed-task-4',
          type: 'text',
          x: 1170,
          y: 475,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-wed-task-5',
          type: 'text',
          x: 1170,
          y: 510,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-wed-meeting-title',
          type: 'text',
          x: 1170,
          y: 560,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '📅 会议安排',
          fontSize: 13,
          fontWeight: 600,
        },
        {
          id: 'el-wed-meeting-1',
          type: 'text',
          x: 1170,
          y: 590,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '• ___:___  ___________________',
          fontSize: 13,
        },
        {
          id: 'el-wed-meeting-2',
          type: 'text',
          x: 1170,
          y: 620,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '• ___:___  ___________________',
          fontSize: 13,
        },
        {
          id: 'el-wed-note-title',
          type: 'text',
          x: 1170,
          y: 665,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '📝 备注',
          fontSize: 13,
          fontWeight: 600,
        },
        {
          id: 'el-wed-note',
          type: 'text',
          x: 1170,
          y: 695,
          width: 420,
          height: 40,
          fill: '#374151',
          text: '___________________________',
          fontSize: 13,
        },
        {
          id: 'el-wed-mood',
          type: 'text',
          x: 1170,
          y: 750,
          width: 420,
          height: 24,
          fill: '#6b7280',
          text: '今日心情：😊 😐 😔       效率评分：___ / 10',
          fontSize: 13,
        },
        {
          id: 'el-thu-bg',
          type: 'rect',
          x: 1660,
          y: 300,
          width: 480,
          height: 700,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-thu-header',
          type: 'rect',
          x: 1660,
          y: 300,
          width: 480,
          height: 50,
          fill: '#ec4899',
          borderTopLeftRadius: 12,
          borderTopRightRadius: 12,
        },
        {
          id: 'el-thu-title',
          type: 'text',
          x: 1680,
          y: 310,
          width: 200,
          height: 30,
          fill: '#ffffff',
          text: '🌟 周四 (Thu)',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-thu-date',
          type: 'text',
          x: 1940,
          y: 315,
          width: 180,
          height: 24,
          fill: '#ffffff',
          text: '___月___日',
          fontSize: 14,
          textAlign: 'right',
        },
        {
          id: 'el-thu-task-1',
          type: 'text',
          x: 1690,
          y: 370,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-thu-task-2',
          type: 'text',
          x: 1690,
          y: 405,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-thu-task-3',
          type: 'text',
          x: 1690,
          y: 440,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-thu-task-4',
          type: 'text',
          x: 1690,
          y: 475,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-thu-task-5',
          type: 'text',
          x: 1690,
          y: 510,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-thu-meeting-title',
          type: 'text',
          x: 1690,
          y: 560,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '📅 会议安排',
          fontSize: 13,
          fontWeight: 600,
        },
        {
          id: 'el-thu-meeting-1',
          type: 'text',
          x: 1690,
          y: 590,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '• ___:___  ___________________',
          fontSize: 13,
        },
        {
          id: 'el-thu-meeting-2',
          type: 'text',
          x: 1690,
          y: 620,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '• ___:___  ___________________',
          fontSize: 13,
        },
        {
          id: 'el-thu-note-title',
          type: 'text',
          x: 1690,
          y: 665,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '📝 备注',
          fontSize: 13,
          fontWeight: 600,
        },
        {
          id: 'el-thu-note',
          type: 'text',
          x: 1690,
          y: 695,
          width: 420,
          height: 40,
          fill: '#374151',
          text: '___________________________',
          fontSize: 13,
        },
        {
          id: 'el-thu-mood',
          type: 'text',
          x: 1690,
          y: 750,
          width: 420,
          height: 24,
          fill: '#6b7280',
          text: '今日心情：😊 😐 😔       效率评分：___ / 10',
          fontSize: 13,
        },
      ],
    },
    {
      name: '每日计划 - 周五六日',
      visible: true,
      locked: false,
      order: 6,
      elements: [
        {
          id: 'el-fri-bg',
          type: 'rect',
          x: 2180,
          y: 300,
          width: 480,
          height: 700,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-fri-header',
          type: 'rect',
          x: 2180,
          y: 300,
          width: 480,
          height: 50,
          fill: '#10b981',
          borderTopLeftRadius: 12,
          borderTopRightRadius: 12,
        },
        {
          id: 'el-fri-title',
          type: 'text',
          x: 2200,
          y: 310,
          width: 200,
          height: 30,
          fill: '#ffffff',
          text: '🎉 周五 (Fri)',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-fri-date',
          type: 'text',
          x: 2460,
          y: 315,
          width: 180,
          height: 24,
          fill: '#ffffff',
          text: '___月___日',
          fontSize: 14,
          textAlign: 'right',
        },
        {
          id: 'el-fri-task-1',
          type: 'text',
          x: 2210,
          y: 370,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-fri-task-2',
          type: 'text',
          x: 2210,
          y: 405,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-fri-task-3',
          type: 'text',
          x: 2210,
          y: 440,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-fri-task-4',
          type: 'text',
          x: 2210,
          y: 475,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-fri-task-5',
          type: 'text',
          x: 2210,
          y: 510,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '□ ___________________________',
          fontSize: 14,
        },
        {
          id: 'el-fri-meeting-title',
          type: 'text',
          x: 2210,
          y: 560,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '📅 会议安排',
          fontSize: 13,
          fontWeight: 600,
        },
        {
          id: 'el-fri-meeting-1',
          type: 'text',
          x: 2210,
          y: 590,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '• ___:___  ___________________',
          fontSize: 13,
        },
        {
          id: 'el-fri-meeting-2',
          type: 'text',
          x: 2210,
          y: 620,
          width: 420,
          height: 24,
          fill: '#374151',
          text: '• ___:___  ___________________',
          fontSize: 13,
        },
        {
          id: 'el-fri-note-title',
          type: 'text',
          x: 2210,
          y: 665,
          width: 200,
          height: 24,
          fill: '#6b7280',
          text: '📝 备注',
          fontSize: 13,
          fontWeight: 600,
        },
        {
          id: 'el-fri-note',
          type: 'text',
          x: 2210,
          y: 695,
          width: 420,
          height: 40,
          fill: '#374151',
          text: '___________________________',
          fontSize: 13,
        },
        {
          id: 'el-fri-mood',
          type: 'text',
          x: 2210,
          y: 750,
          width: 420,
          height: 24,
          fill: '#6b7280',
          text: '今日心情：😊 😐 😔       效率评分：___ / 10',
          fontSize: 13,
        },
        {
          id: 'el-sat-bg',
          type: 'rect',
          x: 2700,
          y: 300,
          width: 220,
          height: 700,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-sat-header',
          type: 'rect',
          x: 2700,
          y: 300,
          width: 220,
          height: 50,
          fill: '#f97316',
          borderTopLeftRadius: 12,
          borderTopRightRadius: 12,
        },
        {
          id: 'el-sat-title',
          type: 'text',
          x: 2710,
          y: 310,
          width: 200,
          height: 30,
          fill: '#ffffff',
          text: '🌤️ 周六',
          fontSize: 16,
          fontWeight: 600,
        },
        {
          id: 'el-sat-task-1',
          type: 'text',
          x: 2720,
          y: 370,
          width: 180,
          height: 24,
          fill: '#374151',
          text: '□ ____________',
          fontSize: 12,
        },
        {
          id: 'el-sat-task-2',
          type: 'text',
          x: 2720,
          y: 400,
          width: 180,
          height: 24,
          fill: '#374151',
          text: '□ ____________',
          fontSize: 12,
        },
        {
          id: 'el-sat-task-3',
          type: 'text',
          x: 2720,
          y: 430,
          width: 180,
          height: 24,
          fill: '#374151',
          text: '□ ____________',
          fontSize: 12,
        },
        {
          id: 'el-sat-task-4',
          type: 'text',
          x: 2720,
          y: 460,
          width: 180,
          height: 24,
          fill: '#374151',
          text: '□ ____________',
          fontSize: 12,
        },
        {
          id: 'el-sun-bg',
          type: 'rect',
          x: 2940,
          y: 300,
          width: 220,
          height: 700,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-sun-header',
          type: 'rect',
          x: 2940,
          y: 300,
          width: 220,
          height: 50,
          fill: '#a855f7',
          borderTopLeftRadius: 12,
          borderTopRightRadius: 12,
        },
        {
          id: 'el-sun-title',
          type: 'text',
          x: 2950,
          y: 310,
          width: 200,
          height: 30,
          fill: '#ffffff',
          text: '🌙 周日',
          fontSize: 16,
          fontWeight: 600,
        },
        {
          id: 'el-sun-task-1',
          type: 'text',
          x: 2960,
          y: 370,
          width: 180,
          height: 24,
          fill: '#374151',
          text: '□ ____________',
          fontSize: 12,
        },
        {
          id: 'el-sun-task-2',
          type: 'text',
          x: 2960,
          y: 400,
          width: 180,
          height: 24,
          fill: '#374151',
          text: '□ ____________',
          fontSize: 12,
        },
        {
          id: 'el-sun-task-3',
          type: 'text',
          x: 2960,
          y: 430,
          width: 180,
          height: 24,
          fill: '#374151',
          text: '□ ____________',
          fontSize: 12,
        },
        {
          id: 'el-sun-task-4',
          type: 'text',
          x: 2960,
          y: 460,
          width: 180,
          height: 24,
          fill: '#374151',
          text: '□ ____________',
          fontSize: 12,
        },
      ],
    },
    {
      name: '周总结',
      visible: true,
      locked: false,
      order: 7,
      elements: [
        {
          id: 'el-summary-bg',
          type: 'rect',
          x: 100,
          y: 1050,
          width: 3060,
          height: 220,
          fill: '#ffffff',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderRadius: 12,
        },
        {
          id: 'el-summary-title',
          type: 'text',
          x: 130,
          y: 1075,
          width: 200,
          height: 30,
          fill: '#059669',
          text: '📊 本周总结',
          fontSize: 18,
          fontWeight: 600,
        },
        {
          id: 'el-done-title',
          type: 'text',
          x: 130,
          y: 1115,
          width: 200,
          height: 24,
          fill: '#059669',
          text: '✅ 已完成',
          fontSize: 14,
          fontWeight: 600,
        },
        {
          id: 'el-done-1',
          type: 'text',
          x: 130,
          y: 1145,
          width: 900,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 13,
        },
        {
          id: 'el-done-2',
          type: 'text',
          x: 130,
          y: 1175,
          width: 900,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 13,
        },
        {
          id: 'el-done-3',
          type: 'text',
          x: 130,
          y: 1205,
          width: 900,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 13,
        },
        {
          id: 'el-improve-title',
          type: 'text',
          x: 1100,
          y: 1115,
          width: 200,
          height: 24,
          fill: '#f59e0b',
          text: '🚀 待改进',
          fontSize: 14,
          fontWeight: 600,
        },
        {
          id: 'el-improve-1',
          type: 'text',
          x: 1100,
          y: 1145,
          width: 900,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 13,
        },
        {
          id: 'el-improve-2',
          type: 'text',
          x: 1100,
          y: 1175,
          width: 900,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 13,
        },
        {
          id: 'el-improve-3',
          type: 'text',
          x: 1100,
          y: 1205,
          width: 900,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 13,
        },
        {
          id: 'el-next-title',
          type: 'text',
          x: 2070,
          y: 1115,
          width: 200,
          height: 24,
          fill: '#3b82f6',
          text: '📌 下周计划',
          fontSize: 14,
          fontWeight: 600,
        },
        {
          id: 'el-next-1',
          type: 'text',
          x: 2070,
          y: 1145,
          width: 900,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 13,
        },
        {
          id: 'el-next-2',
          type: 'text',
          x: 2070,
          y: 1175,
          width: 900,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 13,
        },
        {
          id: 'el-next-3',
          type: 'text',
          x: 2070,
          y: 1205,
          width: 900,
          height: 24,
          fill: '#374151',
          text: '• ________________________________',
          fontSize: 13,
        },
      ],
    },
  ],
};

const templates = [meetingMinutesTemplate, workflowTemplate, weeklyPlanTemplate];

module.exports = {
  templates,
  getTemplateById: (id) => templates.find((t) => t._id === id),
  getTemplates: () => templates,
};